/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.Panels;

import services.UserService;

/**
 *
 * @author ASUS
 */
public class DataUser extends javax.swing.JPanel {

    /**
     * Creates new form InfoTerkini
     */
    public DataUser() {
        initComponents();
        showData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        pnlData = new com.sitardi.CustomComponents.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlView = new com.sitardi.CustomComponents.RoundPanel();
        btnTambah = new com.sitardi.CustomComponents.RoundedButton();
        txtCari = new com.sitardi.CustomComponents.RoundedTextField();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        pnlData.setBackground(new java.awt.Color(96, 2, 0));
        pnlData.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(96, 2, 0));

        pnlView.setBackground(new java.awt.Color(96, 2, 0));

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(pnlView);

        pnlData.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnTambah.setBackground(new java.awt.Color(229, 178, 120));
        btnTambah.setBorder(null);
        btnTambah.setForeground(new java.awt.Color(254, 254, 254));
        btnTambah.setText("Tambah");
        btnTambah.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        btnTambah.setPreferredSize(new java.awt.Dimension(125, 45));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        txtCari.setBackground(new java.awt.Color(254, 254, 254));
        txtCari.setForeground(new java.awt.Color(13, 13, 13));
        txtCari.setText("Cari.........");
        txtCari.setCaretColor(new java.awt.Color(13, 13, 13));
        txtCari.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariMouseClicked(evt);
            }
        });
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(650, 650, 650)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased

        String kataKunci = txtCari.getText().trim();
        services.UserService service = new services.UserService();
        service.tampilUser(pnlView, kataKunci);
        showData(kataKunci);
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyPressed

    private void txtCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMouseClicked
        txtCari.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        com.sitardi.Form.TambahEditUser popUpTambah = new com.sitardi.Form.TambahEditUser(null, true);
        
        // 3. Atur tombol: Matikan tombol Update, Nyalakan tombol Simpan
        popUpTambah.btnUpdate.setEnabled(false);
        popUpTambah.btnSave.setEnabled(true);

        // 4. Munculkan ke tengah layar
        popUpTambah.setLocationRelativeTo(null);
        popUpTambah.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.CustomComponents.RoundedButton btnTambah;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main;
    public static com.sitardi.CustomComponents.RoundPanel pnlData;
    public static com.sitardi.CustomComponents.RoundPanel pnlView;
    private com.sitardi.CustomComponents.RoundedTextField txtCari;
    // End of variables declaration//GEN-END:variables

    public static void showData(String keyword) {
        UserService service = new UserService();
        service.tampilUser(pnlView, keyword);

    }

}
