/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.Panels;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import org.bson.Document;
import services.I18nService;
public class InfoTerkini extends javax.swing.JPanel {

    private Timer realtimeTimer;
    private MongoCollection<Document> pemilihCollection;
    private MongoCollection<Document> logCollection;

    /**
     * Creates new form InfoTerkini
     */
    public InfoTerkini() {
        initComponents();
        
        updateLanguage();
        initDatabase();
        initRealtimeUpdate();
    }

    @Override
    public void addNotify() {
        super.addNotify();
        if (realtimeTimer != null && !realtimeTimer.isRunning()) {
            realtimeTimer.start();
        }
    }

    // Matikan timer jika user berpindah ke panel/menu lain agar menghemat RAM dan CPU Kiosk
    @Override
    public void removeNotify() {
        super.removeNotify();
        if (realtimeTimer != null && realtimeTimer.isRunning()) {
            realtimeTimer.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        infoPemilih = new com.sitardi.CustomComponents.RoundPanel();
        mainInfo = new javax.swing.JLabel();
        subInfoPemilih = new javax.swing.JLabel();
        infoPemilihMasuk = new com.sitardi.CustomComponents.RoundPanel();
        mainInfo1 = new javax.swing.JLabel();
        subInfoMasuk = new javax.swing.JLabel();
        infoPemilihKeluar = new com.sitardi.CustomComponents.RoundPanel();
        mainInfo2 = new javax.swing.JLabel();
        subInfoKeluar = new javax.swing.JLabel();
        roundPanel2 = new com.sitardi.CustomComponents.RoundPanel();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        infoPemilih.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilih.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo.setText("0");

        subInfoPemilih.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        subInfoPemilih.setForeground(new java.awt.Color(254, 254, 254));
        subInfoPemilih.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfoPemilih.setText("Pemilih Terdaftar");

        javax.swing.GroupLayout infoPemilihLayout = new javax.swing.GroupLayout(infoPemilih);
        infoPemilih.setLayout(infoPemilihLayout);
        infoPemilihLayout.setHorizontalGroup(
            infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfoPemilih, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilihLayout.setVerticalGroup(
            infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfoPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        infoPemilihMasuk.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilihMasuk.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo1.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo1.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo1.setText("0");

        subInfoMasuk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        subInfoMasuk.setForeground(new java.awt.Color(254, 254, 254));
        subInfoMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfoMasuk.setText("Pemilih Masuk");

        javax.swing.GroupLayout infoPemilihMasukLayout = new javax.swing.GroupLayout(infoPemilihMasuk);
        infoPemilihMasuk.setLayout(infoPemilihMasukLayout);
        infoPemilihMasukLayout.setHorizontalGroup(
            infoPemilihMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihMasukLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilihMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfoMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilihMasukLayout.setVerticalGroup(
            infoPemilihMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihMasukLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfoMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        infoPemilihKeluar.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilihKeluar.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo2.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo2.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo2.setText("0");

        subInfoKeluar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        subInfoKeluar.setForeground(new java.awt.Color(254, 254, 254));
        subInfoKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfoKeluar.setText("Pemilih Keluar");

        javax.swing.GroupLayout infoPemilihKeluarLayout = new javax.swing.GroupLayout(infoPemilihKeluar);
        infoPemilihKeluar.setLayout(infoPemilihKeluarLayout);
        infoPemilihKeluarLayout.setHorizontalGroup(
            infoPemilihKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihKeluarLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilihKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfoKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilihKeluarLayout.setVerticalGroup(
            infoPemilihKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihKeluarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfoKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        roundPanel2.setBackground(new java.awt.Color(96, 2, 0));

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(infoPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(infoPemilihMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(infoPemilihKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPemilihMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPemilihKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.CustomComponents.RoundPanel infoPemilih;
    private com.sitardi.CustomComponents.RoundPanel infoPemilihKeluar;
    private com.sitardi.CustomComponents.RoundPanel infoPemilihMasuk;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mainInfo;
    private javax.swing.JLabel mainInfo1;
    private javax.swing.JLabel mainInfo2;
    private com.sitardi.CustomComponents.RoundPanel roundPanel2;
    private javax.swing.JLabel subInfoKeluar;
    private javax.swing.JLabel subInfoMasuk;
    private javax.swing.JLabel subInfoPemilih;
    // End of variables declaration//GEN-END:variables

    private void initDatabase() {
        try {
            String mongoURI = System.getProperty("MONGODB_URL");
            com.mongodb.client.MongoClient client = com.mongodb.client.MongoClients.create(mongoURI);

            String dbName = System.getProperty("DATABASE_NAME");
            com.mongodb.client.MongoDatabase db = client.getDatabase(dbName);

            String collPemilih = System.getProperty("COLLP");
            String collLog = System.getProperty("COLLLA");

            this.pemilihCollection = db.getCollection(collPemilih);
            this.logCollection = db.getCollection(collLog); 

            System.out.println("[SUCCESS] Berhasil terhubung ke MongoDB untuk Realtime Dashboard!");

        } catch (Exception e) {
            System.err.println("[ERROR] Gagal inisialisasi DB di InfoTerkini: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void initRealtimeUpdate() {
        realtimeTimer = new Timer(1000, e -> {
            new Thread(() -> {
                try {
                    long totalTerdaftar = dapatkanTotalTerdaftar();
                    long totalMasuk = dapatkanLogHariIni("MASUK");
                    long totalKeluar = dapatkanLogHariIni("KELUAR");

                    SwingUtilities.invokeLater(() -> {
                        mainInfo.setText(String.valueOf(totalTerdaftar));
                        mainInfo1.setText(String.valueOf(totalMasuk));
                        mainInfo2.setText(String.valueOf(totalKeluar));
                    });

                } catch (Exception ex) {
                    System.err.println("Gagal sinkronisasi data realtime: " + ex.getMessage());
                }
            }).start();
        });
    }

    private long dapatkanTotalTerdaftar() {

        if (pemilihCollection != null) {
            return pemilihCollection.countDocuments();
        }
        return 0;
    }

    private long dapatkanLogHariIni(String status) {
        if (logCollection == null) {
            return 0;
        }

        Date awalHariIni = Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant());

        return logCollection.countDocuments(Filters.and(
                Filters.eq("status", status),
                Filters.gte("waktuTap", awalHariIni)
        ));

    }
    
        public void updateLanguage() {
        // Jalankan di Event Dispatch Thread agar aman untuk UI Swing
        javax.swing.SwingUtilities.invokeLater(() -> {
            subInfoPemilih.setText(I18nService.getLocale("ui.label.terdaftar"));
            subInfoMasuk.setText(I18nService.getLocale("ui.label.infomasuk"));
            subInfoKeluar.setText(I18nService.getLocale("ui.label.infokeluar"));
        });
    }

}
