/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.Panels;

import com.sitardi.Form.DashboardAdmin;
import services.I18nService;

/**
 *
 * @author ASUS
 */
public class Pengaturan extends javax.swing.JPanel {

    /**
     * Creates new form InfoTerkini
     */
    public Pengaturan() {
        initComponents();
        syncLanguageToggleState();
        initLanguageListener();
        updateLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        languageToggle2 = new com.sitardi.CustomComponents.LanguageToggle();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 2, 0));
        jLabel1.setText("Bahasa Sistem");

        javax.swing.GroupLayout languageToggle2Layout = new javax.swing.GroupLayout(languageToggle2);
        languageToggle2.setLayout(languageToggle2Layout);
        languageToggle2Layout.setHorizontalGroup(
            languageToggle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        languageToggle2Layout.setVerticalGroup(
            languageToggle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 2, 0));
        jLabel2.setText("PENGATURAN SISTEM");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                                .addComponent(languageToggle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageToggle2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(582, Short.MAX_VALUE))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private com.sitardi.CustomComponents.LanguageToggle languageToggle2;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
private void initLanguageListener() {
        // Mendengarkan event ganti bahasa dari komponen custom LanguageToggle
        languageToggle2.addPropertyChangeListener("language", evt -> {
            String selectedLang = (String) evt.getNewValue();
            java.util.Locale locale;

            // Mapping String dari LanguageToggle ke Objek Locale
            switch (selectedLang) {
                case "English":
                    locale = new java.util.Locale("en");
                    break;
                case "日本語":
                    locale = java.util.Locale.JAPANESE;
                    break;
                case "Bahasa Indonesia":
                default:
                    locale = new java.util.Locale("id", "ID");
                    break;
            }

            // 1. Perbarui Locale di Service I18n
            services.I18nService.setLocale(locale);

            // 2. Perbarui teks di panel Pengaturan ini sendiri
            updateLanguage();

            // 3. Cari DashboardAdmin (Frame Utama) dan perbarui teks menu sidebar-nya
            java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (window instanceof DashboardAdmin) {
                ((DashboardAdmin) window).updateLanguage();
            }
        });
    }

    // Metode untuk memperbarui semua teks di panel Pengaturan
    public void updateLanguage() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            jLabel2.setText(I18nService.getLocale("ui.label.pengaturan"));
            jLabel1.setText(I18nService.getLocale("ui.label.bahasa.sistem"));
        });
    }
    
    private void syncLanguageToggleState() {
        java.util.Locale current = services.I18nService.getCurrentLocale();
        if (current != null) {
            String lang = current.getLanguage();
            
            // Sesuaikan pemanggilan method setter di bawah dengan method yang ada pada LanguageToggle Anda
            // (Misal: setLanguage, setSelectedItem, atau setMasukMode)
            switch (lang) {
                case "en":
                    languageToggle2.setLanguage("English"); 
                    break;
                case "ja":
                    languageToggle2.setLanguage("日本語");
                    break;
                default:
                    languageToggle2.setLanguage("Bahasa Indonesia");
                    break;
            }
            
            // Pastikan komponen menggambar ulang posisinya yang baru
            languageToggle2.repaint();
        }
    }

}
