/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sitardi.Form;

import com.sitardi.Panels.DataPemilih;
import com.sitardi.Panels.DataUser;
import com.sitardi.Panels.InfoTerkini;
import java.awt.BorderLayout;
import java.awt.Color;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import utils.User;
import services.PemilihService;

/**
 *
 * @author ASUS
 */
public class DashboardPetugas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardPetugas.class.getName());

    /**
     * Creates new form Dashboard
     */
    private User userLogged;

    public DashboardPetugas(User user) {
        this.userLogged = user; // Simpan data user yang login ke variabel lokal
        initComponents();

        // Panggil fungsi untuk update tampilan profil
        setProfileData();
        setActiveMenu(btnDashboard);
        AddViews(new InfoTerkini());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roundPanel1 = new com.sitardi.CustomComponents.RoundPanel();
        profileimg = new com.sitardi.CustomComponents.RoundImage();
        lblUsername = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnPresensi = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        btnDataPemilih = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(254, 254, 254));

        sidePanel.setBackground(new java.awt.Color(96, 2, 0));
        sidePanel.setPreferredSize(new java.awt.Dimension(305, 720));

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("SITARDI");

        roundPanel1.setBackground(new java.awt.Color(96, 2, 0));
        roundPanel1.setRoundImage(true);
        roundPanel1.setLayout(new java.awt.BorderLayout());

        profileimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nanami_MBG(My Bini Gwejh).png"))); // NOI18N
        profileimg.setBorderColor(new java.awt.Color(254, 254, 254));
        profileimg.setIsCircle(true);
        roundPanel1.add(profileimg, java.awt.BorderLayout.CENTER);

        lblUsername.setBackground(new java.awt.Color(229, 178, 120));
        lblUsername.setFont(new java.awt.Font("Futura Bk BT", 1, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(229, 178, 120));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Mba Tukam");

        btnDashboard.setBackground(new java.awt.Color(96, 2, 0));
        btnDashboard.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(254, 254, 254));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnPresensi.setBackground(new java.awt.Color(96, 2, 0));
        btnPresensi.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnPresensi.setForeground(new java.awt.Color(254, 254, 254));
        btnPresensi.setText("Presensi");
        btnPresensi.setBorder(null);
        btnPresensi.setBorderPainted(false);
        btnPresensi.setContentAreaFilled(false);
        btnPresensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresensiActionPerformed(evt);
            }
        });

        btnPengaturan.setBackground(new java.awt.Color(96, 2, 0));
        btnPengaturan.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(254, 254, 254));
        btnPengaturan.setText("Pengaturan");
        btnPengaturan.setBorder(null);
        btnPengaturan.setBorderPainted(false);
        btnPengaturan.setContentAreaFilled(false);
        btnPengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengaturanActionPerformed(evt);
            }
        });

        btnDataPemilih.setBackground(new java.awt.Color(96, 2, 0));
        btnDataPemilih.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnDataPemilih.setForeground(new java.awt.Color(254, 254, 254));
        btnDataPemilih.setText("Data Pemilih");
        btnDataPemilih.setBorder(null);
        btnDataPemilih.setBorderPainted(false);
        btnDataPemilih.setContentAreaFilled(false);
        btnDataPemilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataPemilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPemilihActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(96, 2, 0));
        btnLogout.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(254, 254, 254));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7))
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDataPemilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPresensi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addGap(67, 67, 67)
                .addComponent(btnDashboard)
                .addGap(35, 35, 35)
                .addComponent(btnPresensi)
                .addGap(35, 35, 35)
                .addComponent(btnDataPemilih)
                .addGap(40, 40, 40)
                .addComponent(btnPengaturan)
                .addGap(145, 145, 145)
                .addComponent(btnLogout)
                .addGap(67, 67, 67))
        );

        pnlKonten.setBackground(new java.awt.Color(254, 254, 254));
        pnlKonten.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlKonten, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        setActiveMenu(btnDashboard);
        AddViews(new InfoTerkini());

// TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login fromLogin = new Login();
        fromLogin.setLocationRelativeTo(null);
        fromLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresensiActionPerformed
        // TODO add your handling code here:
        setActiveMenu(btnPresensi);
        AddViews(new DataUser());
    }//GEN-LAST:event_btnPresensiActionPerformed

    private void btnPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaturanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPengaturanActionPerformed

    private void btnDataPemilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPemilihActionPerformed
        // TODO add your handling code here:
        AddViews(new DataPemilih());
        setActiveMenu(btnDataPemilih);
    }//GEN-LAST:event_btnDataPemilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardPetugas(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataPemilih;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.JButton btnPresensi;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel main;
    private static javax.swing.JPanel pnlKonten;
    private com.sitardi.CustomComponents.RoundImage profileimg;
    private com.sitardi.CustomComponents.RoundPanel roundPanel1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    private void setProfileData() {
        if (userLogged != null) {
            // 1. Set Nama
            lblUsername.setText(userLogged.getName());

            // 2. Set Foto Profil dari URL Cloud
            String urlString = userLogged.getUrl_img();

            if (urlString != null && !urlString.isEmpty()) {
                // Kita gunakan Thread agar UI tidak "freeze" saat mendownload gambar
                new Thread(() -> {
                    try {
                        URL url = new URL(urlString);
                        // Membaca gambar dari URL
                        java.awt.Image image = ImageIO.read(url);

                        if (image != null) {
                            // Scaling agar pas dengan ukuran komponen profileimg
                            int width = profileimg.getWidth() > 0 ? profileimg.getWidth() : 100;
                            int height = profileimg.getHeight() > 0 ? profileimg.getHeight() : 100;

                            java.awt.Image scaledImage = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);

                            // Update UI harus dilakukan di Event Dispatch Thread
                            javax.swing.SwingUtilities.invokeLater(() -> {
                                profileimg.setIcon(new javax.swing.ImageIcon(scaledImage));
                            });
                        }
                    } catch (Exception e) {
                        System.err.println("Gagal memuat gambar dari Cloud: " + e.getMessage());
                        // Opsional: Set gambar default jika gagal
                        // profileimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_user.png")));
                    }
                }).start();
            }
        }
    }

    public static void showData(String key) {
        PemilihService P = new PemilihService();
        P.tampilPemilih(pnlKonten, key);
    }

    private void AddViews(JPanel Dt) {
        if (pnlKonten.getComponentCount() > 0) {
            pnlKonten.removeAll();
        }
        pnlKonten.add(Dt, BorderLayout.CENTER);
        pnlKonten.revalidate();
        pnlKonten.repaint();
    }

    private void setActiveMenu(javax.swing.JButton activeBtn) {
        // 1. Daftar semua tombol menu kamu
        javax.swing.JButton[] menus = {btnDashboard, btnPresensi, btnDataPemilih, btnPengaturan};

        // 2. Loop semua tombol
        for (javax.swing.JButton btn : menus) {
            if (btn == activeBtn) {
                // Warna saat aktif (Menyala/Gold)
                btn.setForeground(Color.decode("#E5B278"));
                // Opsional: Jika ingin memberi bold saat aktif
                btn.setFont(new java.awt.Font("Futura Bk BT", 1, 20));
            } else {
                // Warna standar (Putih)
                btn.setForeground(Color.decode("#FEFEFE"));
                btn.setFont(new java.awt.Font("Futura Bk BT", 0, 20));
            }
        }
    }

}
