/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sitardi.Form;

import com.sitardi.Serial.SerialDtHandler;
import services.JamDigitalService;
import services.LogAbsensiService;
import services.PemilihService;
import services.SerialService;
import services.UserService;
import utils.Pemilih;
import utils.User;

/**
 *
 * @author ASUS
 */
public class Presensi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presensi.class.getName());
    private javax.swing.JFrame parentDashboard;
    private String statusAbsensi;
    private LogAbsensiService logAbsensiService;
    private SerialService serialService;
    private PemilihService pemilihService;
    private SerialDtHandler<String> rfidHandler;
    private Thread delayThread;

    /**
     * Creates new form Presensi
     *
     * @param isMasukMode
     */
    public Presensi(javax.swing.JFrame parentDashboard, boolean isMasukMode) {
        this.parentDashboard = parentDashboard;
        this.statusAbsensi = isMasukMode ? "MASUK" : "KELUAR";

        initComponents();
        initJamDigital();
        initAbsensiAndBroadcast();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roundPanel1 = new com.sitardi.CustomComponents.RoundPanel();
        roundPanel2 = new com.sitardi.CustomComponents.RoundPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtKonfirmasi = new javax.swing.JLabel();
        txtSelamat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlRealtime = new com.sitardi.CustomComponents.RoundPanel();
        lblTimeTitle = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        lblHariTanggalBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        pnlInputManual = new com.sitardi.CustomComponents.RoundPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        inptNIK = new javax.swing.JTextField();
        btnMasuk = new com.sitardi.CustomComponents.RoundedButton();
        btnTest = new com.sitardi.CustomComponents.RoundedButton();
        btnClose = new javax.swing.JLabel();
        lblBtnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(254, 254, 254));

        sidePanel.setBackground(new java.awt.Color(96, 2, 0));
        sidePanel.setPreferredSize(new java.awt.Dimension(495, 720));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("SITARDI");

        roundPanel1.setBackground(new java.awt.Color(229, 178, 120));
        roundPanel1.setPreferredSize(new java.awt.Dimension(380, 290));

        roundPanel2.setBackground(new java.awt.Color(150, 30, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card.png"))); // NOI18N

        txtNama.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(254, 254, 254));
        txtNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNama.setText("SCAN KARTU");

        txtKonfirmasi.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtKonfirmasi.setForeground(new java.awt.Color(254, 254, 254));
        txtKonfirmasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKonfirmasi.setText("Letakan kartumu mu pada alat scanner ");

        txtSelamat.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtSelamat.setForeground(new java.awt.Color(254, 254, 254));
        txtSelamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSelamat.setText("untuk mencatat kehadiran");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9))
                    .addComponent(txtSelamat, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKonfirmasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSelamat)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Tips:");

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("1. Pastikan kartumu dalam keadaan bersih sebelum di scan");

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("2. Jika belum memiliki E-KTP bisa melakukan absensi manual ");

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("dengan mengetikan NIK pada kolom sebelah.");

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("3. Jika mengalami kesulitan segera meminta bantuan kepada ");

        jLabel8.setFont(new java.awt.Font("Futura Md BT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("panitia yang bertugas.");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRealtime.setBackground(new java.awt.Color(150, 30, 31));
        pnlRealtime.setPreferredSize(new java.awt.Dimension(595, 185));

        lblTimeTitle.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        lblTimeTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTimeTitle.setText("Waktu saat ini");

        lblWaktu.setFont(new java.awt.Font("Futura Md BT", 1, 82)); // NOI18N
        lblWaktu.setForeground(new java.awt.Color(254, 254, 254));
        lblWaktu.setText("07:24:34");

        lblHariTanggalBulan.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        lblHariTanggalBulan.setForeground(new java.awt.Color(254, 254, 254));
        lblHariTanggalBulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHariTanggalBulan.setText("Selasa, 30 September");

        lblTahun.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        lblTahun.setForeground(new java.awt.Color(254, 254, 254));
        lblTahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTahun.setText("2026");

        javax.swing.GroupLayout pnlRealtimeLayout = new javax.swing.GroupLayout(pnlRealtime);
        pnlRealtime.setLayout(pnlRealtimeLayout);
        pnlRealtimeLayout.setHorizontalGroup(
            pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRealtimeLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeTitle)
                    .addGroup(pnlRealtimeLayout.createSequentialGroup()
                        .addComponent(lblWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHariTanggalBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        pnlRealtimeLayout.setVerticalGroup(
            pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealtimeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTimeTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlRealtimeLayout.createSequentialGroup()
                        .addComponent(lblHariTanggalBulan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTahun))
                    .addComponent(lblWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlInputManual.setBackground(new java.awt.Color(150, 30, 31));
        pnlInputManual.setPreferredSize(new java.awt.Dimension(595, 185));

        lblTitle1.setFont(new java.awt.Font("Futura Md BT", 1, 21)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle1.setText("CATAT PRESENSI MANUAL");

        lblTitle2.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle2.setText("Masukan NIK:");

        inptNIK.setPreferredSize(new java.awt.Dimension(71, 40));

        btnMasuk.setBackground(new java.awt.Color(96, 2, 0));
        btnMasuk.setForeground(new java.awt.Color(254, 254, 254));
        btnMasuk.setText("Masuk");
        btnMasuk.setBorderColor(new java.awt.Color(229, 178, 120));
        btnMasuk.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        btnMasuk.setRadius(15);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(96, 2, 0));
        btnTest.setForeground(new java.awt.Color(254, 254, 254));
        btnTest.setText("Tes Scan");
        btnTest.setBorderColor(new java.awt.Color(229, 178, 120));
        btnTest.setFont(new java.awt.Font("Futura Bk BT", 1, 18)); // NOI18N
        btnTest.setRadius(15);
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputManualLayout = new javax.swing.GroupLayout(pnlInputManual);
        pnlInputManual.setLayout(pnlInputManualLayout);
        pnlInputManualLayout.setHorizontalGroup(
            pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputManualLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle2)
                    .addComponent(lblTitle1)
                    .addComponent(inptNIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlInputManualLayout.setVerticalGroup(
            pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputManualLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inptNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        lblBtnClose.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lblBtnClose.setForeground(new java.awt.Color(96, 2, 0));
        lblBtnClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBtnClose.setText("Keluar");
        lblBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlRealtime, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addComponent(pnlInputManual, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(lblBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRealtime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pnlInputManual, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked

        if (serialService != null && rfidHandler != null) {
            serialService.removeHandler(rfidHandler);
        }

        this.parentDashboard.setVisible(true);

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // 1. Ambil teks dan hilangkan spasi berlebih
        String nikInput = inptNIK.getText().trim();

        // 2. Cek apakah tidak kosong
        if (!nikInput.isEmpty()) {
            if (serialService != null) {
                // Masuk ke jalur pipeline absensi
                serialService.broadcast(nikInput);
            }
            // Bersihkan field HANYA di sini
            inptNIK.setText("");
        } else {
            // Tampilkan pesan error jika benar-benar kosong
            updateUiWithDelay("INPUT KOSONG", "Silakan masukkan NIK Anda", "pada kolom yang tersedia.");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        SerialService.getInstance().broadcast("333");
    }//GEN-LAST:event_btnTestActionPerformed

    private void lblBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCloseMouseClicked
        if (serialService != null && rfidHandler != null) {
            serialService.removeHandler(rfidHandler);
        }

        this.parentDashboard.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Berikan nilai default (misal: true) agar form bisa di-test run langsung
            new Presensi(null, true).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private com.sitardi.CustomComponents.RoundedButton btnMasuk;
    private com.sitardi.CustomComponents.RoundedButton btnTest;
    private javax.swing.JTextField inptNIK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBtnClose;
    private javax.swing.JLabel lblHariTanggalBulan;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTimeTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JPanel main;
    private com.sitardi.CustomComponents.RoundPanel pnlInputManual;
    private com.sitardi.CustomComponents.RoundPanel pnlRealtime;
    private com.sitardi.CustomComponents.RoundPanel roundPanel1;
    private com.sitardi.CustomComponents.RoundPanel roundPanel2;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel txtKonfirmasi;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtSelamat;
    // End of variables declaration//GEN-END:variables

    private void initJamDigital() {
        // Thread untuk Jam (Format: Jam:Menit:Detik)
        JamDigitalService jam = new JamDigitalService(lblWaktu, "HH:mm:ss");
        jam.getThread().start();

        // Thread untuk Hari, Tanggal, dan Bulan (Format: Hari, Tanggal Bulan)
        JamDigitalService tanggal = new JamDigitalService(lblHariTanggalBulan, "EEEE, dd MMMM");
        tanggal.getThread().start();

        // Thread untuk Tahun (Format: Tahun 4 digit)
        JamDigitalService tahun = new JamDigitalService(lblTahun, "yyyy");
        tahun.getThread().start();
    }

    private void initAbsensiAndBroadcast() {
        logAbsensiService = new LogAbsensiService();
        pemilihService = new PemilihService();
        serialService = SerialService.getInstance();

        // A. REGISTER HANDLER UNTUK MERESPON SETIAP BROADCAST DATA
        rfidHandler = new SerialDtHandler<String>() {
            @Override
            public void onDataReceived(String data) {
                // Proses absensi (Baik dari scan kartu asli maupun input manual)
                prosesAbsensiSistem(data);
            }
        };
        serialService.addHandler(rfidHandler);

        // B. TOMBOL MANUAL (btnMasuk) SEKARANG IKUT MELAKUKAN BROADCAST
        // C. KONEKSIKAN KE PORT SCANNER
        String targetPort = "COM3";
        int baudRate = 9600;
        serialService.connect(targetPort, baudRate);
    }

    /**
     * Jalur pemrosesan tunggal (Unified Pipeline) untuk mencatat log dan update
     * UI
     */
    private void prosesAbsensiSistem(String nomorIdentitas) {
        try {
            // 1. VALIDASI USER: Apakah terdaftar di sistem?
            Pemilih pemilihTerdaftar = pemilihService.cariBerdasarkanIdentitas(nomorIdentitas);

            if (pemilihTerdaftar == null) {
                updateUiWithDelay(
                        "TIDAK TERDAFTAR",
                        "ID / NIK tidak dikenali.",
                        "Silakan hubungi panitia/admin."
                );
                return;
            }

            String namaUser = pemilihTerdaftar.getNama_lengkap().toUpperCase();

            // 2. PERIKSA RIWAYAT ABSENSI HARI INI
            boolean sudahAbsenMasuk = logAbsensiService.cekStatusAbsenHariIni(nomorIdentitas, "MASUK");
            boolean sudahAbsenKeluar = logAbsensiService.cekStatusAbsenHariIni(nomorIdentitas, "KELUAR");

            // SITUASI A: User sudah menyelesaikan kedua proses (MASUK & KELUAR)
            if (sudahAbsenMasuk && sudahAbsenKeluar) {
                updateUiWithDelay(
                        "AKSES DITOLAK",
                        namaUser,
                        "Anda sudah selesai melakukan absensi!"
                );
                return;
            }

            // SITUASI B: Alat sedang dalam mode "MASUK"
            if (this.statusAbsensi.equals("MASUK")) {
                if (sudahAbsenMasuk) {
                    updateUiWithDelay(
                            "SUDAH ABSEN",
                            namaUser,
                            "Anda sudah melakukan absensi MASUK."
                    );
                    return; // Blokir tap masuk berulang
                }
            } // SITUASI C: Alat sedang dalam mode "KELUAR"
            else if (this.statusAbsensi.equals("KELUAR")) {
                if (!sudahAbsenMasuk) {
                    updateUiWithDelay(
                            "AKSES DITOLAK",
                            namaUser,
                            "Belum bisa ABSEN KELUAR karena Anda belum ABSEN MASUK."
                    );
                    return; // Blokir jika langsung lompat ke absen keluar
                }
                if (sudahAbsenKeluar) {
                    updateUiWithDelay(
                            "SUDAH ABSEN",
                            namaUser,
                            "Anda sudah melakukan absensi KELUAR."
                    );
                    return; // Blokir tap keluar berulang
                }
            }

            // 3. EKSEKUSI: Jika lolos semua validasi di atas, catat log absensi baru
            logAbsensiService.catatLog(nomorIdentitas, this.statusAbsensi);

            // 4. UPDATE UI: Berhasil
            updateUiWithDelay(
                    this.statusAbsensi + " SUKSES!",
                    namaUser,
                    "Terima kasih, data berhasil disimpan."
            );

        } catch (Exception e) {
            updateUiWithDelay(
                    "SISTEM GAGAL",
                    "Gagal memproses absensi.",
                    e.getMessage()
            );
        }
    }

    /**
     * Mengupdate teks panel informasi dan meresetnya ke default secara
     * Thread-Safe setelah 3 detik
     */
    private void updateUiWithDelay(String nama, String konfirmasi, String selamat) {
        // Jika ada delay thread yang sedang berjalan dari tap sebelumnya, hentikan paksa!
        if (delayThread != null && delayThread.isAlive()) {
            delayThread.interrupt();
        }

        // Buat thread baru untuk menangani jeda tampilan informasi (Kiosk Mode)
        delayThread = new Thread(() -> {
            try {
                // Update UI awal di dalam Event Dispatch Thread (EDT)
                java.awt.EventQueue.invokeLater(() -> {
                    txtNama.setText(nama);
                    txtKonfirmasi.setText(konfirmasi);
                    txtSelamat.setText(selamat);
                });

                // Tahan informasi di layar selama 3 detik
                Thread.sleep(3000);

                // Kembalikan ke teks panduan default (Thread-Safe)
                java.awt.EventQueue.invokeLater(() -> {
                    txtNama.setText("SCAN KARTU");
                    txtKonfirmasi.setText("Letakan kartumu pada alat scanner ");
                    txtSelamat.setText("untuk mencatat kehadiran");
                });

            } catch (InterruptedException e) {
                // Diabaikan jika di-interrupt oleh aktivitas tap baru sebelum 3 detik usai
            }
        });

        delayThread.setName("KioskDelayThread");
        delayThread.setDaemon(true); // Agar thread mati otomatis saat aplikasi ditutup
        delayThread.start();
    }

}
