/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sitardi.Form;

import com.sitardi.Serial.SerialDtHandler;
import services.I18nService;
import services.JamDigitalService;
import services.LogAbsensiService;
import services.PemilihService;
import services.SerialService;
import services.UserService;
import utils.Pemilih;
import utils.User;

/**
 *
 * @author ASUS
 */
public class Presensi extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presensi.class.getName());
    private javax.swing.JFrame parentDashboard;
    private String statusAbsensi;
    private LogAbsensiService logAbsensiService;
    private SerialService serialService;
    private PemilihService pemilihService;
    private SerialDtHandler<String> rfidHandler;
    private Thread delayThread;

    /**
     * Creates new form Presensi
     *
     * @param isMasukMode
     */
    public Presensi(javax.swing.JFrame parentDashboard, boolean isMasukMode) {
        this.parentDashboard = parentDashboard;
        this.statusAbsensi = isMasukMode ? "MASUK" : "KELUAR";
        updateLanguage();
        initComponents();
        initJamDigital();
        initAbsensiAndBroadcast();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roundPanel1 = new com.sitardi.CustomComponents.RoundPanel();
        roundPanel2 = new com.sitardi.CustomComponents.RoundPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtKonfirmasi = new javax.swing.JLabel();
        txtSelamat = new javax.swing.JLabel();
        lblTips = new javax.swing.JLabel();
        lblTips1 = new javax.swing.JLabel();
        lblTips2 = new javax.swing.JLabel();
        lblTips21 = new javax.swing.JLabel();
        lblTips3 = new javax.swing.JLabel();
        lblTips31 = new javax.swing.JLabel();
        pnlRealtime = new com.sitardi.CustomComponents.RoundPanel();
        lblTimeTitle = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();
        lblHariTanggalBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        pnlInputManual = new com.sitardi.CustomComponents.RoundPanel();
        lblTitleManual = new javax.swing.JLabel();
        lblMasukanNIK = new javax.swing.JLabel();
        inptNIK = new javax.swing.JTextField();
        btnMasuk = new com.sitardi.CustomComponents.RoundedButton();
        btnTest = new com.sitardi.CustomComponents.RoundedButton();
        btnClose = new javax.swing.JLabel();
        lblBtnClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(254, 254, 254));

        sidePanel.setBackground(new java.awt.Color(96, 2, 0));
        sidePanel.setPreferredSize(new java.awt.Dimension(495, 720));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("SITARDI");

        roundPanel1.setBackground(new java.awt.Color(229, 178, 120));
        roundPanel1.setPreferredSize(new java.awt.Dimension(380, 290));

        roundPanel2.setBackground(new java.awt.Color(150, 30, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card.png"))); // NOI18N

        txtNama.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(254, 254, 254));
        txtNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNama.setText("SCAN KARTU");

        txtKonfirmasi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtKonfirmasi.setForeground(new java.awt.Color(254, 254, 254));
        txtKonfirmasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtKonfirmasi.setText("Letakan kartumu mu pada alat scanner ");

        txtSelamat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtSelamat.setForeground(new java.awt.Color(254, 254, 254));
        txtSelamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSelamat.setText("untuk mencatat kehadiran");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9))
                    .addComponent(txtSelamat, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKonfirmasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSelamat)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTips.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTips.setForeground(new java.awt.Color(254, 254, 254));
        lblTips.setText("Tips:");

        lblTips1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTips1.setForeground(new java.awt.Color(254, 254, 254));
        lblTips1.setText("1. Pastikan kartumu dalam keadaan bersih sebelum di scan");

        lblTips2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTips2.setForeground(new java.awt.Color(254, 254, 254));
        lblTips2.setText("2. Jika belum memiliki E-KTP bisa melakukan absensi manual ");

        lblTips21.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTips21.setForeground(new java.awt.Color(254, 254, 254));
        lblTips21.setText("dengan mengetikan NIK pada kolom sebelah.");

        lblTips3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTips3.setForeground(new java.awt.Color(254, 254, 254));
        lblTips3.setText("3. Jika mengalami kesulitan segera meminta bantuan kepada ");

        lblTips31.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTips31.setForeground(new java.awt.Color(254, 254, 254));
        lblTips31.setText("panitia yang bertugas.");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTips31, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTips21, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTips2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTips, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTips1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTips3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblTips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTips1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTips2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTips21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTips3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTips31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRealtime.setBackground(new java.awt.Color(150, 30, 31));
        pnlRealtime.setPreferredSize(new java.awt.Dimension(595, 185));

        lblTimeTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTimeTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTimeTitle.setText("Waktu saat ini");

        lblWaktu.setFont(new java.awt.Font("SansSerif", 1, 72)); // NOI18N
        lblWaktu.setForeground(new java.awt.Color(254, 254, 254));
        lblWaktu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWaktu.setText("07:24:34 AM");

        lblHariTanggalBulan.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblHariTanggalBulan.setForeground(new java.awt.Color(254, 254, 254));
        lblHariTanggalBulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHariTanggalBulan.setText("Selasa, 30 September");

        lblTahun.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblTahun.setForeground(new java.awt.Color(254, 254, 254));
        lblTahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTahun.setText("2026");

        javax.swing.GroupLayout pnlRealtimeLayout = new javax.swing.GroupLayout(pnlRealtime);
        pnlRealtime.setLayout(pnlRealtimeLayout);
        pnlRealtimeLayout.setHorizontalGroup(
            pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRealtimeLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimeTitle)
                    .addGroup(pnlRealtimeLayout.createSequentialGroup()
                        .addComponent(lblWaktu)
                        .addGap(18, 18, 18)
                        .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHariTanggalBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );
        pnlRealtimeLayout.setVerticalGroup(
            pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealtimeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTimeTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlRealtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRealtimeLayout.createSequentialGroup()
                        .addComponent(lblHariTanggalBulan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTahun))
                    .addComponent(lblWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlInputManual.setBackground(new java.awt.Color(150, 30, 31));
        pnlInputManual.setPreferredSize(new java.awt.Dimension(595, 185));

        lblTitleManual.setFont(new java.awt.Font("SansSerif", 1, 21)); // NOI18N
        lblTitleManual.setForeground(new java.awt.Color(254, 254, 254));
        lblTitleManual.setText("CATAT PRESENSI MANUAL");

        lblMasukanNIK.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblMasukanNIK.setForeground(new java.awt.Color(254, 254, 254));
        lblMasukanNIK.setText("Masukan NIK:");

        inptNIK.setPreferredSize(new java.awt.Dimension(71, 40));

        btnMasuk.setBackground(new java.awt.Color(96, 2, 0));
        btnMasuk.setForeground(new java.awt.Color(254, 254, 254));
        btnMasuk.setText("Masuk");
        btnMasuk.setBorderColor(new java.awt.Color(229, 178, 120));
        btnMasuk.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnMasuk.setRadius(15);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(96, 2, 0));
        btnTest.setForeground(new java.awt.Color(254, 254, 254));
        btnTest.setText("Tes Scan");
        btnTest.setBorderColor(new java.awt.Color(229, 178, 120));
        btnTest.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnTest.setRadius(15);
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputManualLayout = new javax.swing.GroupLayout(pnlInputManual);
        pnlInputManual.setLayout(pnlInputManualLayout);
        pnlInputManualLayout.setHorizontalGroup(
            pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputManualLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMasukanNIK)
                    .addComponent(lblTitleManual)
                    .addComponent(inptNIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlInputManualLayout.setVerticalGroup(
            pnlInputManualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputManualLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitleManual)
                .addGap(18, 18, 18)
                .addComponent(lblMasukanNIK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inptNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        lblBtnClose.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblBtnClose.setForeground(new java.awt.Color(96, 2, 0));
        lblBtnClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBtnClose.setText("Keluar");
        lblBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlRealtime, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addComponent(pnlInputManual, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(lblBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRealtime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pnlInputManual, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked

        if (serialService != null && rfidHandler != null) {
            serialService.removeHandler(rfidHandler);
        }

        this.parentDashboard.setVisible(true);

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // 1. Ambil teks dan hilangkan spasi berlebih
        String nikInput = inptNIK.getText().trim();

        // 2. Cek apakah tidak kosong
        if (!nikInput.isEmpty()) {
            if (serialService != null) {
                // Masuk ke jalur pipeline absensi
                serialService.broadcast(nikInput);
            }
            // Bersihkan field HANYA di sini
            inptNIK.setText("");
        } else {
            // Tampilkan pesan error jika benar-benar kosong
            updateUiWithDelay("INPUT KOSONG", "Silakan masukkan NIK Anda", "pada kolom yang tersedia.");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        SerialService.getInstance().broadcast("333");
    }//GEN-LAST:event_btnTestActionPerformed

    private void lblBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCloseMouseClicked
        if (serialService != null && rfidHandler != null) {
            serialService.removeHandler(rfidHandler);
        }

        this.parentDashboard.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblBtnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Berikan nilai default (misal: true) agar form bisa di-test run langsung
            new Presensi(null, true).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private com.sitardi.CustomComponents.RoundedButton btnMasuk;
    private com.sitardi.CustomComponents.RoundedButton btnTest;
    private javax.swing.JTextField inptNIK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBtnClose;
    private javax.swing.JLabel lblHariTanggalBulan;
    private javax.swing.JLabel lblMasukanNIK;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTimeTitle;
    private javax.swing.JLabel lblTips;
    private javax.swing.JLabel lblTips1;
    private javax.swing.JLabel lblTips2;
    private javax.swing.JLabel lblTips21;
    private javax.swing.JLabel lblTips3;
    private javax.swing.JLabel lblTips31;
    private javax.swing.JLabel lblTitleManual;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JPanel main;
    private com.sitardi.CustomComponents.RoundPanel pnlInputManual;
    private com.sitardi.CustomComponents.RoundPanel pnlRealtime;
    private com.sitardi.CustomComponents.RoundPanel roundPanel1;
    private com.sitardi.CustomComponents.RoundPanel roundPanel2;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel txtKonfirmasi;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtSelamat;
    // End of variables declaration//GEN-END:variables

    private void initJamDigital() {
        // 1. Dapatkan objek Locale yang sedang aktif saat ini
        // Catatan: Jika I18nService Anda belum memiliki method ini, Anda bisa menggunakan `java.util.Locale.getDefault()`
        java.util.Locale currentLocale = services.I18nService.getCurrentLocale();

        // 2. Ambil pola format (pattern) dinamis dari file properties
        String patternWaktu = services.I18nService.getLocale("date.format.time");
        String patternTanggal = services.I18nService.getLocale("date.format.date");
        String patternTahun = services.I18nService.getLocale("date.format.year");

        // 3. Jalankan Thread dengan pattern dan locale yang sesuai
        // Thread untuk Jam (Format: Jam:Menit:Detik)
        JamDigitalService jam = new JamDigitalService(lblWaktu, patternWaktu, currentLocale);
        jam.getThread().start();

        // Thread untuk Hari, Tanggal, dan Bulan (Format menyesuaikan negara)
        JamDigitalService tanggal = new JamDigitalService(lblHariTanggalBulan, patternTanggal, currentLocale);
        tanggal.getThread().start();

        // Thread untuk Tahun (Format menyesuaikan negara)
        JamDigitalService tahun = new JamDigitalService(lblTahun, patternTahun, currentLocale);
        tahun.getThread().start();
    }

    private void initAbsensiAndBroadcast() {
        logAbsensiService = new LogAbsensiService();
        pemilihService = new PemilihService();
        serialService = SerialService.getInstance();

        // A. REGISTER HANDLER UNTUK MERESPON SETIAP BROADCAST DATA
        rfidHandler = new SerialDtHandler<String>() {
            @Override
            public void onDataReceived(String data) {
                // Proses absensi (Baik dari scan kartu asli maupun input manual)
                prosesAbsensiSistem(data);
            }
        };
        serialService.addHandler(rfidHandler);

        // B. TOMBOL MANUAL (btnMasuk) SEKARANG IKUT MELAKUKAN BROADCAST
        // C. KONEKSIKAN KE PORT SCANNER
        String targetPort = "COM3";
        int baudRate = 9600;
        serialService.connect(targetPort, baudRate);
    }

    private void prosesAbsensiSistem(String nomorIdentitas) {
        try {
            // 1. VALIDASI USER: Apakah terdaftar di sistem?
            Pemilih pemilihTerdaftar = pemilihService.cariBerdasarkanIdentitas(nomorIdentitas);

            if (pemilihTerdaftar == null) {
                updateUiWithDelay(
                        services.I18nService.getLocale("absen.tdk_terdaftar.title"),
                        services.I18nService.getLocale("absen.tdk_terdaftar.desc1"),
                        services.I18nService.getLocale("absen.tdk_terdaftar.desc2")
                );
                return;
            }

            String namaUser = pemilihTerdaftar.getNama_lengkap().toUpperCase();

            // 2. PERIKSA RIWAYAT ABSENSI HARI INI
            boolean sudahAbsenMasuk = logAbsensiService.cekStatusAbsenHariIni(nomorIdentitas, "MASUK");
            boolean sudahAbsenKeluar = logAbsensiService.cekStatusAbsenHariIni(nomorIdentitas, "KELUAR");

            // SITUASI A: User sudah menyelesaikan kedua proses (MASUK & KELUAR)
            if (sudahAbsenMasuk && sudahAbsenKeluar) {
                updateUiWithDelay(
                        services.I18nService.getLocale("absen.akses_ditolak.title"),
                        namaUser,
                        services.I18nService.getLocale("absen.selesai.desc")
                );
                return;
            }

            // SITUASI B: Alat sedang dalam mode "MASUK"
            if (this.statusAbsensi.equals("MASUK")) {
                if (sudahAbsenMasuk) {
                    updateUiWithDelay(
                            services.I18nService.getLocale("absen.sudah_absen.title"),
                            namaUser,
                            services.I18nService.getLocale("absen.sudah_masuk.desc")
                    );
                    return; // Blokir tap masuk berulang
                }
            } // SITUASI C: Alat sedang dalam mode "KELUAR"
            else if (this.statusAbsensi.equals("KELUAR")) {
                if (!sudahAbsenMasuk) {
                    updateUiWithDelay(
                            services.I18nService.getLocale("absen.akses_ditolak.title"),
                            namaUser,
                            services.I18nService.getLocale("absen.belum_masuk.desc")
                    );
                    return; // Blokir jika langsung lompat ke absen keluar
                }
                if (sudahAbsenKeluar) {
                    updateUiWithDelay(
                            services.I18nService.getLocale("absen.sudah_absen.title"),
                            namaUser,
                            services.I18nService.getLocale("absen.sudah_keluar.desc")
                    );
                    return; // Blokir tap keluar berulang
                }
            }

            // 3. EKSEKUSI: Jika lolos semua validasi di atas, catat log absensi baru
            logAbsensiService.catatLog(nomorIdentitas, this.statusAbsensi);

            // 4. UPDATE UI: Berhasil
            // Menentukan judul sukses secara dinamis berdasarkan mode alat
            String titleSukses = this.statusAbsensi.equals("MASUK")
                    ? services.I18nService.getLocale("absen.masuk_sukses.title")
                    : services.I18nService.getLocale("absen.keluar_sukses.title");

            updateUiWithDelay(
                    titleSukses,
                    namaUser,
                    services.I18nService.getLocale("absen.sukses.desc")
            );

        } catch (Exception e) {
            updateUiWithDelay(
                    services.I18nService.getLocale("absen.sistem_gagal.title"),
                    services.I18nService.getLocale("absen.sistem_gagal.desc"),
                    e.getMessage() // Exception message dibiarkan default untuk debugging
            );
        }
    }

    /**
     * Mengupdate teks panel informasi dan meresetnya ke default secara
     * Thread-Safe setelah 3 detik
     */
    private void updateUiWithDelay(String nama, String konfirmasi, String selamat) {
        // Jika ada delay thread yang sedang berjalan dari tap sebelumnya, hentikan paksa!
        if (delayThread != null && delayThread.isAlive()) {
            delayThread.interrupt();
        }

        // Buat thread baru untuk menangani jeda tampilan informasi (Kiosk Mode)
        delayThread = new Thread(() -> {
            try {
                // Update UI awal di dalam Event Dispatch Thread (EDT)
                java.awt.EventQueue.invokeLater(() -> {
                    txtNama.setText(nama);
                    txtKonfirmasi.setText(konfirmasi);
                    txtSelamat.setText(selamat);
                });

                // Tahan informasi di layar selama 3 detik
                Thread.sleep(3000);

                // Kembalikan ke teks panduan default (Thread-Safe)
                java.awt.EventQueue.invokeLater(() -> {
                    txtNama.setText(I18nService.getLocale("lbl.scn.crd"));
                    txtKonfirmasi.setText(I18nService.getLocale("lbl.order"));
                    txtSelamat.setText(I18nService.getLocale("lbl.cause"));
                });

            } catch (InterruptedException e) {
                // Diabaikan jika di-interrupt oleh aktivitas tap baru sebelum 3 detik usai
            }
        });

        delayThread.setName("KioskDelayThread");
        delayThread.setDaemon(true); // Agar thread mati otomatis saat aplikasi ditutup
        delayThread.start();
    }

    public void updateLanguage() {
        // Jalankan di Event Dispatch Thread agar aman untuk UI Swing
        javax.swing.SwingUtilities.invokeLater(() -> {
            lblTimeTitle.setText(I18nService.getLocale("lbl.time.tittle"));
            lblMasukanNIK.setText(I18nService.getLocale("lbl.input.nik"));
            lblTitleManual.setText(I18nService.getLocale("lbl.manual.inpt"));
            btnMasuk.setText(I18nService.getLocale("btn.checkin"));
            btnTest.setText(I18nService.getLocale("btn.test.scan"));
            lblBtnClose.setText(I18nService.getLocale("btn.exit"));
            txtNama.setText(I18nService.getLocale("lbl.scn.crd"));
            txtKonfirmasi.setText(I18nService.getLocale("lbl.order"));
            txtSelamat.setText(I18nService.getLocale("lbl.cause"));
            lblTips.setText(I18nService.getLocale("lbl.tips"));
            lblTips1.setText(I18nService.getLocale("lbl.tips1"));
            lblTips2.setText(I18nService.getLocale("lbl.tips2"));
            lblTips21.setText(I18nService.getLocale("lbl.tips2.1"));
            lblTips3.setText(I18nService.getLocale("lbl.tips3"));
            lblTips31.setText(I18nService.getLocale("lbl.tips3.1"));
        });
    }

}
