/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sitardi.Form;

import com.sitardi.Panels.DataPemilih;
import static com.sitardi.Panels.DataPemilih.showData;
import java.text.ParseException;
import utils.Pemilih;
import utils.User;
import services.PemilihService;
import services.UserService;

/**
 *
 * @author ASUS
 */
public class TambahEditUser extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahEditUser.class.getName());

    /**
     * Creates new form TambahEdit
     *
     * @param parent
     * @param modal
     */
    public TambahEditUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        txtUrl.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                loadProfileImage(txtUrl.getText().trim());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        TxtNIK = new javax.swing.JTextField();
        TxtUsername = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        Txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        roundImage1 = new com.sitardi.CustomComponents.RoundImage();
        TxtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(96, 2, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(229, 178, 120));
        btnSave.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(254, 254, 254));
        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(150, 30, 31));
        btnUpdate.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(254, 254, 254));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        TxtNIK.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        TxtNIK.setPreferredSize(new java.awt.Dimension(220, 25));
        TxtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNIKActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        TxtUsername.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        TxtUsername.setMinimumSize(new java.awt.Dimension(70, 20));
        TxtUsername.setPreferredSize(new java.awt.Dimension(220, 25));
        TxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        TxtNama.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        TxtNama.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel1.add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        Txtemail.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        Txtemail.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel1.add(Txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NIK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 58, -1));

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 87, -1));

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Role");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, 21));

        cmbRole.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Petugas" }));
        cmbRole.setPreferredSize(new java.awt.Dimension(220, 25));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TAMBAH /EDIT DATA USER");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 21, 187, 28));

        jLabel9.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Url Img");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 52, 20));

        txtUrl.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        txtUrl.setPreferredSize(new java.awt.Dimension(220, 25));
        txtUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUrlKeyReleased(evt);
            }
        });
        jPanel1.add(txtUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        roundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nanami_MBG(My Bini Gwejh).png"))); // NOI18N
        roundImage1.setIsCircle(true);
        jPanel1.add(roundImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 61, -1, -1));

        TxtPassword.setText("jPasswordField1");
        TxtPassword.setPreferredSize(new java.awt.Dimension(220, 25));
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari inputan
            User u = new User();
            u.setNik(TxtNIK.getText().trim());
            u.setUsername(TxtUsername.getText().trim());
            u.setName(TxtNama.getText().trim());
            u.setEmail(Txtemail.getText().trim());
            u.setPassword(new String(TxtPassword.getPassword()));
            u.setRole(cmbRole.getSelectedItem().toString());
            u.setUrl_img(txtUrl.getText().trim());

            // 2. Validasi sederhana
            if (u.getNik().isEmpty() || u.getUsername().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "NIK dan Username tidak boleh kosong!");
                return;
            }

            // 3. Eksekusi Service
            UserService service = new UserService();
            service.tambahUser(u);

            // 4. Feedback & Refresh Tabel
            javax.swing.JOptionPane.showMessageDialog(this, "User berhasil disimpan!");
            com.sitardi.Panels.DataUser.showData(""); // Refresh tabel di panel utama
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    private void TxtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNIKActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            User u = new User();
            u.setNik(TxtNIK.getText().trim()); // NIK digunakan sebagai kunci pencarian
            u.setUsername(TxtUsername.getText().trim());
            u.setName(TxtNama.getText().trim());
            u.setEmail(Txtemail.getText().trim());
            u.setPassword(new String(TxtPassword.getPassword()));
            u.setRole(cmbRole.getSelectedItem().toString());
            u.setUrl_img(txtUrl.getText().trim());

            UserService service = new UserService();
            service.updateUser(u);

            javax.swing.JOptionPane.showMessageDialog(this, "Data User berhasil diperbarui!");
            com.sitardi.Panels.DataUser.showData("");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtUrlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlKeyReleased
        loadProfileImage(txtUrl.getText().trim());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TambahEditUser dialog = new TambahEditUser(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.dispose();
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TxtNIK;
    public javax.swing.JTextField TxtNama;
    public javax.swing.JPasswordField TxtPassword;
    public javax.swing.JTextField TxtUsername;
    public javax.swing.JTextField Txtemail;
    public javax.swing.JButton btnSave;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public com.sitardi.CustomComponents.RoundImage roundImage1;
    public javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    public void loadProfileImage(String urlString) {
        if (urlString == null || urlString.trim().isEmpty()) {
            // Jika URL kosong, bisa dikembalikan ke gambar default
            roundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nanami_MBG(My Bini Gwejh).png")));
            return;
        }

        // Jalankan di thread terpisah agar UI tidak freeze
        new Thread(() -> {
            try {
                java.net.URL url = new java.net.URL(urlString);
                java.awt.Image image = javax.imageio.ImageIO.read(url);

                if (image != null) {
                    // Ambil ukuran komponen roundImage1
                    int width = roundImage1.getWidth();
                    int height = roundImage1.getHeight();

                    // Jika width/height masih 0 (karena belum render), beri ukuran default
                    if (width <= 0) {
                        width = 130;
                    }
                    if (height <= 0) {
                        height = 130;
                    }

                    // Scale gambar agar pas dengan komponen
                    java.awt.Image scaledImage = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);

                    // Update UI di Event Dispatch Thread
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        roundImage1.setIcon(new javax.swing.ImageIcon(scaledImage));
                    });
                }
            } catch (Exception e) {
                System.err.println("Gagal memuat gambar dari URL: " + e.getMessage());
                // Jika error, biarkan gambar lama atau set placeholder
            }
        }).start();
    }

}
