/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.sitardi.sitardi.Dialog;

/**
 *
 * @author ASUS
 */
public class EditUser extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditUser.class.getName());

    /**
     * Creates new form EditUser
     */
    public EditUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        lblForm = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUrl = new javax.swing.JLabel();
        inptUsername = new javax.swing.JTextField();
        inptName = new javax.swing.JTextField();
        inptEmail = new javax.swing.JTextField();
        inptPassword = new javax.swing.JTextField();
        inptUrl = new javax.swing.JTextField();
        btnSimpan = new com.sitardi.sitardi.CustomComponents.RoundedButton();
        btnBatal = new com.sitardi.sitardi.CustomComponents.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlUtama.setBackground(new java.awt.Color(96, 2, 0));

        lblForm.setFont(new java.awt.Font("Futura Md BT", 1, 20)); // NOI18N
        lblForm.setForeground(new java.awt.Color(254, 254, 254));
        lblForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForm.setText("Edit");

        lblUsername.setBackground(new java.awt.Color(254, 254, 254));
        lblUsername.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(254, 254, 254));
        lblUsername.setText("Username     :");

        lblName.setBackground(new java.awt.Color(254, 254, 254));
        lblName.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(254, 254, 254));
        lblName.setText("Name            :");

        lblEmail.setBackground(new java.awt.Color(254, 254, 254));
        lblEmail.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(254, 254, 254));
        lblEmail.setText("Email             :");

        lblPassword.setBackground(new java.awt.Color(254, 254, 254));
        lblPassword.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(254, 254, 254));
        lblPassword.setText("Password      :");

        lblUrl.setBackground(new java.awt.Color(254, 254, 254));
        lblUrl.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        lblUrl.setForeground(new java.awt.Color(254, 254, 254));
        lblUrl.setText("Url Image     :");

        inptUsername.setText("jTextField1");
        inptUsername.setBorder(null);

        inptName.setText("jTextField1");
        inptName.setBorder(null);

        inptEmail.setText("jTextField1");
        inptEmail.setBorder(null);

        inptPassword.setText("jTextField1");
        inptPassword.setBorder(null);

        inptUrl.setText("jTextField1");
        inptUrl.setBorder(null);

        btnSimpan.setBackground(new java.awt.Color(229, 178, 120));
        btnSimpan.setForeground(new java.awt.Color(254, 254, 254));
        btnSimpan.setText("Simpan");
        btnSimpan.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N

        btnBatal.setBackground(new java.awt.Color(150, 30, 31));
        btnBatal.setForeground(new java.awt.Color(254, 254, 254));
        btnBatal.setText("Batal");
        btnBatal.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblUsername)
                                .addGap(18, 18, 18)
                                .addComponent(inptUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblEmail)
                                    .addComponent(lblPassword)
                                    .addComponent(lblUrl))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inptName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inptUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblForm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblForm)
                .addGap(54, 54, 54)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(inptUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inptName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(33, 33, 33)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(inptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(inptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUrl)
                            .addComponent(inptUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        getContentPane().add(pnlUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditUser dialog = new EditUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.sitardi.CustomComponents.RoundedButton btnBatal;
    private com.sitardi.sitardi.CustomComponents.RoundedButton btnSimpan;
    private javax.swing.JTextField inptEmail;
    private javax.swing.JTextField inptName;
    private javax.swing.JTextField inptPassword;
    private javax.swing.JTextField inptUrl;
    private javax.swing.JTextField inptUsername;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlUtama;
    // End of variables declaration//GEN-END:variables
}
