/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.sitardi.Panels;

/**
 *
 * @author ASUS
 */
public class DataUser extends javax.swing.JPanel {

    /**
     * Creates new form InfoTerkini
     */
    public DataUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        pnlData = new com.sitardi.sitardi.CustomComponents.RoundPanel();
        btnTambah = new com.sitardi.sitardi.CustomComponents.RoundedButton();
        btnEdit = new com.sitardi.sitardi.CustomComponents.RoundedButton();
        btnHapus = new com.sitardi.sitardi.CustomComponents.RoundedButton();
        txtCari = new com.sitardi.sitardi.CustomComponents.RoundedTextField();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        pnlData.setBackground(new java.awt.Color(96, 2, 0));

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        btnTambah.setBackground(new java.awt.Color(229, 178, 120));
        btnTambah.setBorder(null);
        btnTambah.setForeground(new java.awt.Color(254, 254, 254));
        btnTambah.setText("Tambah");
        btnTambah.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        btnTambah.setPreferredSize(new java.awt.Dimension(125, 45));

        btnEdit.setBackground(new java.awt.Color(150, 30, 31));
        btnEdit.setBorder(null);
        btnEdit.setForeground(new java.awt.Color(254, 254, 254));
        btnEdit.setText("Edit");
        btnEdit.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(125, 45));

        btnHapus.setBackground(new java.awt.Color(96, 2, 0));
        btnHapus.setBorder(null);
        btnHapus.setForeground(new java.awt.Color(254, 254, 254));
        btnHapus.setText("Hapus");
        btnHapus.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        btnHapus.setPreferredSize(new java.awt.Dimension(125, 45));

        txtCari.setBackground(new java.awt.Color(254, 254, 254));
        txtCari.setForeground(new java.awt.Color(13, 13, 13));
        txtCari.setText("Cari.........");
        txtCari.setCaretColor(new java.awt.Color(13, 13, 13));
        txtCari.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        txtCari.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.sitardi.CustomComponents.RoundedButton btnEdit;
    private com.sitardi.sitardi.CustomComponents.RoundedButton btnHapus;
    private com.sitardi.sitardi.CustomComponents.RoundedButton btnTambah;
    private javax.swing.JPanel main;
    private com.sitardi.sitardi.CustomComponents.RoundPanel pnlData;
    private com.sitardi.sitardi.CustomComponents.RoundedTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
