/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.sitardi.Panels;

/**
 *
 * @author ASUS
 */
public class InfoTerkini extends javax.swing.JPanel {

    /**
     * Creates new form InfoTerkini
     */
    public InfoTerkini() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        infoPemilih = new com.sitardi.sitardi.CustomComponents.RoundPanel();
        mainInfo = new javax.swing.JLabel();
        subInfo = new javax.swing.JLabel();
        infoPemilih1 = new com.sitardi.sitardi.CustomComponents.RoundPanel();
        mainInfo1 = new javax.swing.JLabel();
        subInfo1 = new javax.swing.JLabel();
        infoPemilih2 = new com.sitardi.sitardi.CustomComponents.RoundPanel();
        mainInfo2 = new javax.swing.JLabel();
        subInfo2 = new javax.swing.JLabel();
        roundPanel2 = new com.sitardi.sitardi.CustomComponents.RoundPanel();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        infoPemilih.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilih.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo.setText("10");

        subInfo.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        subInfo.setForeground(new java.awt.Color(254, 254, 254));
        subInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfo.setText("Pemilih Terdaftar");

        javax.swing.GroupLayout infoPemilihLayout = new javax.swing.GroupLayout(infoPemilih);
        infoPemilih.setLayout(infoPemilihLayout);
        infoPemilihLayout.setHorizontalGroup(
            infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilihLayout.setVerticalGroup(
            infoPemilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilihLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        infoPemilih1.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilih1.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo1.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo1.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo1.setText("10");

        subInfo1.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        subInfo1.setForeground(new java.awt.Color(254, 254, 254));
        subInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfo1.setText("Pemilih Terdaftar");

        javax.swing.GroupLayout infoPemilih1Layout = new javax.swing.GroupLayout(infoPemilih1);
        infoPemilih1.setLayout(infoPemilih1Layout);
        infoPemilih1Layout.setHorizontalGroup(
            infoPemilih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilih1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilih1Layout.setVerticalGroup(
            infoPemilih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilih1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        infoPemilih2.setBackground(new java.awt.Color(96, 2, 0));
        infoPemilih2.setPreferredSize(new java.awt.Dimension(267, 148));

        mainInfo2.setFont(new java.awt.Font("Futura Md BT", 1, 48)); // NOI18N
        mainInfo2.setForeground(new java.awt.Color(254, 254, 254));
        mainInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainInfo2.setText("10");

        subInfo2.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        subInfo2.setForeground(new java.awt.Color(254, 254, 254));
        subInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subInfo2.setText("Pemilih Terdaftar");

        javax.swing.GroupLayout infoPemilih2Layout = new javax.swing.GroupLayout(infoPemilih2);
        infoPemilih2.setLayout(infoPemilih2Layout);
        infoPemilih2Layout.setHorizontalGroup(
            infoPemilih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilih2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(infoPemilih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        infoPemilih2Layout.setVerticalGroup(
            infoPemilih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPemilih2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(mainInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        roundPanel2.setBackground(new java.awt.Color(96, 2, 0));

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(infoPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(infoPemilih1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(infoPemilih2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPemilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPemilih1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPemilih2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.sitardi.CustomComponents.RoundPanel infoPemilih;
    private com.sitardi.sitardi.CustomComponents.RoundPanel infoPemilih1;
    private com.sitardi.sitardi.CustomComponents.RoundPanel infoPemilih2;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mainInfo;
    private javax.swing.JLabel mainInfo1;
    private javax.swing.JLabel mainInfo2;
    private com.sitardi.sitardi.CustomComponents.RoundPanel roundPanel2;
    private javax.swing.JLabel subInfo;
    private javax.swing.JLabel subInfo1;
    private javax.swing.JLabel subInfo2;
    // End of variables declaration//GEN-END:variables
}
