/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sitardi.sitardi.Panels;

/**
 *
 * @author ASUS
 */
public class Pengaturan extends javax.swing.JPanel {

    /**
     * Creates new form InfoTerkini
     */
    public Pengaturan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxCustom1 = new com.sitardi.sitardi.CustomComponents.ComboBoxCustom();

        setLayout(new java.awt.BorderLayout());

        main.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 2, 0));
        jLabel1.setText("Pengaturan");

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 2, 0));
        jLabel2.setText("Bahasa Sistem");

        comboBoxCustom1.setForeground(new java.awt.Color(96, 2, 0));
        comboBoxCustom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bahasa Indonesia", "English" }));
        comboBoxCustom1.setArrowColor(new java.awt.Color(144, 2, 0));
        comboBoxCustom1.setBorderColor(new java.awt.Color(96, 2, 0));
        comboBoxCustom1.setFocusable(false);
        comboBoxCustom1.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                        .addComponent(comboBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(532, Short.MAX_VALUE))
        );

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.sitardi.sitardi.CustomComponents.ComboBoxCustom comboBoxCustom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
