/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sitardi.sitardi.Form;

import com.sitardi.sitardi.Panels.DataUser;
import com.sitardi.sitardi.Panels.InfoTerkini;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        AddViews(new InfoTerkini());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roundPanel1 = new com.sitardi.sitardi.CustomComponents.RoundPanel();
        roundImage1 = new com.sitardi.sitardi.CustomComponents.RoundImage();
        lblUsername = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnDataPetugas = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        btnDataPemilih = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlKonten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(254, 254, 254));

        sidePanel.setBackground(new java.awt.Color(96, 2, 0));
        sidePanel.setPreferredSize(new java.awt.Dimension(305, 720));

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("SITARDI");

        roundPanel1.setBackground(new java.awt.Color(96, 2, 0));
        roundPanel1.setRoundImage(true);
        roundPanel1.setLayout(new java.awt.BorderLayout());

        roundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nanami_MBG(My Bini Gwejh).png"))); // NOI18N
        roundImage1.setBorderColor(new java.awt.Color(254, 254, 254));
        roundImage1.setIsCircle(true);
        roundPanel1.add(roundImage1, java.awt.BorderLayout.CENTER);

        lblUsername.setBackground(new java.awt.Color(229, 178, 120));
        lblUsername.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(229, 178, 120));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Mba Tukam");

        btnDashboard.setBackground(new java.awt.Color(96, 2, 0));
        btnDashboard.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(254, 254, 254));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDataPetugas.setBackground(new java.awt.Color(96, 2, 0));
        btnDataPetugas.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnDataPetugas.setForeground(new java.awt.Color(254, 254, 254));
        btnDataPetugas.setText("Data Petugas");
        btnDataPetugas.setBorder(null);
        btnDataPetugas.setBorderPainted(false);
        btnDataPetugas.setContentAreaFilled(false);
        btnDataPetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPetugasActionPerformed(evt);
            }
        });

        btnPengaturan.setBackground(new java.awt.Color(96, 2, 0));
        btnPengaturan.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(254, 254, 254));
        btnPengaturan.setText("Pengaturan");
        btnPengaturan.setBorder(null);
        btnPengaturan.setBorderPainted(false);
        btnPengaturan.setContentAreaFilled(false);
        btnPengaturan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengaturanActionPerformed(evt);
            }
        });

        btnDataPemilih.setBackground(new java.awt.Color(96, 2, 0));
        btnDataPemilih.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnDataPemilih.setForeground(new java.awt.Color(254, 254, 254));
        btnDataPemilih.setText("Data Pemilih");
        btnDataPemilih.setBorder(null);
        btnDataPemilih.setBorderPainted(false);
        btnDataPemilih.setContentAreaFilled(false);
        btnDataPemilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataPemilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPemilihActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(96, 2, 0));
        btnLogout.setFont(new java.awt.Font("Futura Bk BT", 0, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(254, 254, 254));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7))
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDataPemilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDataPetugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addGap(67, 67, 67)
                .addComponent(btnDashboard)
                .addGap(35, 35, 35)
                .addComponent(btnDataPetugas)
                .addGap(35, 35, 35)
                .addComponent(btnDataPemilih)
                .addGap(40, 40, 40)
                .addComponent(btnPengaturan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(67, 67, 67))
        );

        pnlKonten.setBackground(new java.awt.Color(254, 254, 254));
        pnlKonten.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlKonten, javax.swing.GroupLayout.DEFAULT_SIZE, 1136, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        btnDashboard.setForeground(Color.decode("#E5B278"));
        btnDataPetugas.setForeground(Color.decode("#FEFEFE"));
                AddViews(new InfoTerkini());
// TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDataPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPetugasActionPerformed
        // TODO add your handling code here:
        btnDashboard.setForeground(Color.decode("#FEFEFE"));
        btnDataPetugas.setForeground(Color.decode("#E5B278"));
        AddViews(new DataUser());
    }//GEN-LAST:event_btnDataPetugasActionPerformed

    private void btnPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengaturanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPengaturanActionPerformed

    private void btnDataPemilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPemilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataPemilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataPemilih;
    private javax.swing.JButton btnDataPetugas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlKonten;
    private com.sitardi.sitardi.CustomComponents.RoundImage roundImage1;
    private com.sitardi.sitardi.CustomComponents.RoundPanel roundPanel1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    private void AddViews(JPanel Dt) {
        if (pnlKonten.getComponentCount() > 0) {
            pnlKonten.removeAll();
        }
        pnlKonten.add(Dt, BorderLayout.CENTER);
        pnlKonten.revalidate();
        pnlKonten.repaint();
    }

}
